chore: slightly better factoring of stack frame code (#2012)
PR #2004 was accidentally shipped without 2 commits that should have
been in there, because of:

```
$ git push
To github.com:aws/aws-cdk-cli.git
 ! [rejected]          huijbers/shared-report-code -> huijbers/shared-report-code (non-fast-forward)
error: failed to push some refs to 'github.com:aws/aws-cdk-cli.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart.
```

😳 oops.

In any case, here they are.


---
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache-2.0 license